{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graph.fullname" . }}-api
  labels:
    {{- include "graph.labels" . | nindent 4 }}
    app: {{ include "graph.fullname" . }}-api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "graph.selectorLabels" . | nindent 6 }}
      app: {{ include "graph.fullname" . }}-api
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "graph.labels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ include "graph.fullname" . }}-api
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "graph.api.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{- include "graph.api.imageName" . }}"
          ports:
            - containerPort: 8080
          env:
            - name: AGEDB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "graph.fullname" . }}-app
                  key: port
            - name: AGEDB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "graph.fullname" . }}-app
                  key: dbname
            - name: AGEDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "graph.fullname" . }}-app
                  key: username
            - name: AGEDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "graph.fullname" . }}-app
                  key: password
            - name: ConnectionStrings__agedb
              value: "Server={{ include "graph.fullname" . }}-rw,{{ include "graph.fullname" . }}-ro;Port=$(AGEDB_PORT);Database=$(AGEDB_NAME);Username=$(AGEDB_USERNAME);Password=$(AGEDB_PASSWORD)"
            - name: Logging__LogLevel__Default
              value: {{ .Values.api.logLevel | quote }}
            {{- if .Values.api.openTelemetry.enabled }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.api.openTelemetry.serviceName | default (printf "%s-api" (include "graph.fullname" .)) | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.api.openTelemetry.exporterEndpoint | quote }}
            {{- end }}
            {{- list .Values.api.config "" | include "recurseFlattenMap" | nindent 12 }}
            {{- with .Values.api.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.api.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- with .Values.api.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.api.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}